### ISSUE TITLE
Content List Pagination

### ISSUE THREAD

**Issue by lasseborly** [Arth101/battlefield1UI#16]
For ex. blog functionality we need to paginate posts to multiple pages. How does the pagination controls look?

**Comment by Arth101** [comment]
![screenshot from 2016-10-16 17-10-34](https://cloud.githubusercontent.com/assets/8166831/19418413/b610b29c-93c3-11e6-99ae-f116871a973e.png)

**Comment by lasseborly** [comment]
Solves it beautifully!
