### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by lasseborly** [Arth101/battlefield1UI#7]
Encompases:
- Text Inputs
- Textarea
- Radio buttons
- Checkboxes
- Dropdown/Select

Will help and submit own PR's and should be labeled as feature/enhancement.

**Comment by Arth101** [comment]
Check it out @ https://arth101.github.io/BFUI/example/components.html
![screenshot from 2016-10-16 17-27-53](https://cloud.githubusercontent.com/assets/8166831/19435015/d706461a-9468-11e6-8b5e-05c7ffdbce6c.png)
![screenshot from 2016-10-17 12-52-42](https://cloud.githubusercontent.com/assets/8166831/19435014/d70654f2-9468-11e6-9eb2-b8477543297f.png)
![screenshot from 2016-10-17 12-52-49](https://cloud.githubusercontent.com/assets/8166831/19435013/d7057eec-9468-11e6-9165-e5f86d6ea2d4.png)
![screenshot from 2016-10-17 12-52-55](https://cloud.githubusercontent.com/assets/8166831/19435016/d70785d4-9468-11e6-954a-92cc766cb055.png)

**Comment by lasseborly** [comment]
Looks good!
