### ISSUE TITLE
Lists (tables)

### ISSUE THREAD

**Issue by lasseborly** [Arth101/battlefield1UI#8]
I do not want to say tables but kinda like tables.

![list](https://cloud.githubusercontent.com/assets/2671660/18938055/03a10c54-85f6-11e6-82a4-531aa40d35e9.png)

Will help and submit own PR's and should be labeled as feature/enhancement.

**Comment by Arth101** [comment]
![screenshot from 2016-10-16 17-27-53](https://cloud.githubusercontent.com/assets/8166831/19418531/e37d8028-93c5-11e6-9f15-61aa342d9448.png)

**Comment by lasseborly** [comment]
Looks great.
